### PR TITLE
fix: Update the package.json files so that correct Node version gets selected for the Nodejs sample apps

### PR DESCRIPTION
**Pull request by Akash-Nayak**
Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

### CODE REVIEW

**Comment by Akash-Nayak** [comment]
If no node version is mentioned in the package.json file, Move2Kube will select the default node version which will be the latest version from the [nodeversions.yaml](https://github.com/konveyor/move2kube/blob/main/assets/built-in/transformers/dockerfilegenerator/mappings/nodeversions.yaml). Our sample nodejs applications aren't compatible with node v16 and above, so I have added the node version constraint to the package.json file.

**Comment by HarikrishnanBalagopal** [comment]
`Our sample nodejs applications aren't compatible with node v16 and above`

The NodeJS sample in language-platforms is compatible, we run end-to-end tests which deploy them on a cluster and return 200 OK.

Also even if it is true that they can't run with the latest NodeJS then that is a bug that needs to be fixed. The sample apps are simple static web servers for the most part, there is no reason to have complex version restrictions

**Review by HarikrishnanBalagopal — CHANGES_REQUESTED** [review]
If there are issues with making these samples work with Node 18 and beyond we should fix those bugs. Adding the version constraint does not make sense for such simple static web server samples.

**Comment by Akash-Nayak** [comment]
> If there are issues with making these samples work with Node 18 and beyond we should fix those bugs. Adding the version constraint does not make sense for such simple static web server samples.

I deployed the NodeJS sample with Node 16 and it didn't work on the OpenShift cluster. But, then I deployed the same NodeJS sample to Kubernetes cluster and it worked. I think the end-to-end tests deploys it on a Kubernetes cluster and return 200 OK.

Screenshot 2022-10-28 at 9 26 18 AM

Screenshot 2022-10-28 at 9 22 57 AM

**Comment by Akash-Nayak** [comment]
With `registry.access.redhat.com/ubi8/nodejs-14` and `registry.access.redhat.com/ubi8/nodejs-12` image, it works on both OpenShift as well as Kubernetes cluster.

Screenshot 2022-10-28 at 9 35 04 AM

Screenshot 2022-10-28 at 9 37 42 AM

**Comment by HarikrishnanBalagopal** [comment]
> > If there are issues with making these samples work with Node 18 and beyond we should fix those bugs. Adding the version constraint does not make sense for such simple static web server samples.
> 
> I deployed the NodeJS sample with Node 16 (`registry.access.redhat.com/ubi8/nodejs-16`) and it didn't work on the OpenShift cluster. But, then I deployed the same NodeJS sample to Kubernetes cluster and it worked. I think the end-to-end tests deploys it on a Kubernetes cluster and return 200 OK.
> 
> Screenshot 2022-10-28 at 9 26 18 AM
> 
> Screenshot 2022-10-28 at 9 22 57 AM

This just confirms that it's not a Node version issue but an Openshift issue (since the same code works on Kubernetes).
Regardless add the version constraint is not the correct thing to do. If there are bugs that are preventing the same code from running on Openshift we should fix it.

**Comment by HarikrishnanBalagopal** [comment]
> > If there are issues with making these samples work with Node 18 and beyond we should fix those bugs. Adding the version constraint does not make sense for such simple static web server samples.
> 
> I deployed the NodeJS sample with Node 16 (`registry.access.redhat.com/ubi8/nodejs-16`) and it didn't work on the OpenShift cluster. But, then I deployed the same NodeJS sample to Kubernetes cluster and it worked. I think the end-to-end tests deploys it on a Kubernetes cluster and return 200 OK.
> 
> Screenshot 2022-10-28 at 9 26 18 AM
> 
> Screenshot 2022-10-28 at 9 22 57 AM

Looking at the error, it's just a common permissions issue that people face:
https://stackoverflow.com/questions/42363105/permission-denied-mkdir-in-container-on-openshift

We can fix it by adding the proper `chmod` for `/opt/app-root/src/.npm`.
Another way to fix it is by changing where Node writes the logs to.

**Comment by HarikrishnanBalagopal** [comment]
Fixed during session over Webex.

**Comment by Akash-Nayak** [comment]
https://github.com/konveyor/move2kube-demos/pull/197

**Pull request closed without merging**
